name: Astro CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [ latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Verify Bun version
        run: bun --version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint

      - name: Build the Astro project
        run: bun run build
